name: Code Scan

on:
  workflow_call:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

   #   - name: Secret Scan with Gitleaks
   #     uses: gitleaks/gitleaks-action@v2
   #     env:
   #       GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

      - name: Secret Scan with TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: .
          output: trufflehog-results.json

      - name: Vulnerability Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          ignore-unfixed: true
          severity: HIGH,CRITICAL

      - name: Code Quality with SonarCloud
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=SQ1-Devops_demo-repository
            -Dsonar.organization=SQ1-Devops
            -Dsonar.host.url=https://sonarcloud.io
