# .github/workflows/code-scan.yml
name: Code Scan

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Secret Scan with Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml # Optional custom config

      - name: Vulnerability Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          ignore-unfixed: true
          severity: HIGH,CRITICAL

      - name: Code Quality with SonarCloud (Free for public repos)
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectKey: your_project_key
          organization: your_org
