name: Gitleaks Secret Scan

on:
  workflow_dispatch:

jobs:
  gitleaks-scan:
    name: Run Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Gitleaks Binary
        id: cache-gitleaks
        uses: actions/cache@v4
        with:
          path: ~/.cache/gitleaks
          key: gitleaks-${{ runner.os }}-v8

      - name: Download Gitleaks if not cached
        if: steps.cache-gitleaks.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.cache/gitleaks
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o ~/.cache/gitleaks/gitleaks
          chmod +x ~/.cache/gitleaks/gitleaks

      - name: Add Gitleaks to PATH
        run: echo "$HOME/.cache/gitleaks" >> $GITHUB_PATH
      - name: Run Gitleaks
        run: |
          gitleaks detect --source=. --report-format=json --report-path=gitleaks-report.json

      - name: Upload Gitleaks Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
