name: Gitleaks Secret Scan

on:
  workflow_dispatch:

jobs:
  gitleaks-scan:
    name: Run Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2.3.4
        with:
          args: detect --source=. --report-format=json --report-path=gitleaks-report.json

      - name: Upload Gitleaks Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
